name: spendo
description: Personal expense tracker — graduation project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Charts
  fl_chart: ^0.68.0
  google_fonts: ^6.1.0

  # State (Phase 2 — add now so structure is ready)
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Routing
  go_router: ^13.0.0

  # Local storage & DI
  get_it: ^7.7.0
  drift: ^2.14.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.0

  # Utils
  intl: ^0.20.2
  pdf: ^3.10.0
  share_plus: ^7.2.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.14.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true   # enables l10n generation

  assets:
    - assets/fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Spendo.png"
  adaptive_icon_foreground: "assets/icons/Spendo.png"
  adaptive_icon_background: "#7C3AED"
  min_sdk_android: 21
